version: '3.8'

services:
  bootnode:
    build:
      context: ./besu
      dockerfile: Dockerfile
    container_name: besu-bootnode
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303/tcp"
      - "30303:30303/udp"
    volumes:
      - ./node-configs/bootnode:/opt/besu/data
      - ./config:/opt/besu/config
    command: |
      --genesis-file=/opt/besu/config/genesis.json
      --data-path=/opt/besu/data
      --node-private-key-file=/opt/besu/data/key
      --rpc-http-enabled=true
      --rpc-http-host=0.0.0.0
      --rpc-http-port=8545
      --rpc-http-cors-origins="*"
      --rpc-ws-enabled=true
      --rpc-ws-host=0.0.0.0
      --rpc-ws-port=8546
      --host-allowlist="*"
      --p2p-enabled=true
      --p2p-host=0.0.0.0
      --p2p-port=30303
      --network-id=1337
      --logging=INFO
      --permissions-accounts-config-enabled=true
      --permissions-accounts-config-file=/opt/besu/config/permissions.json
    networks:
      - besu-network

  validator1:
    build:
      context: ./besu
      dockerfile: Dockerfile
    container_name: besu-validator1
    ports:
      - "8547:8545"
      - "30304:30303/tcp"
      - "30304:30303/udp"
    volumes:
      - ./node-configs/node1:/opt/besu/data
      - ./config:/opt/besu/config
    depends_on:
      - bootnode
    command: |
      --genesis-file=/opt/besu/config/genesis.json
      --data-path=/opt/besu/data
      --node-private-key-file=/opt/besu/data/key
      --bootnodes=enode://$(cat ./node-configs/bootnode/enode)@bootnode:30303
      --rpc-http-enabled=true
      --rpc-http-host=0.0.0.0
      --rpc-http-port=8545
      --rpc-http-cors-origins="*"
      --host-allowlist="*"
      --p2p-enabled=true
      --p2p-host=0.0.0.0
      --p2p-port=30303
      --network-id=1337
      --logging=INFO
      --permissions-accounts-config-enabled=true
      --permissions-accounts-config-file=/opt/besu/config/permissions.json
    networks:
      - besu-network

  validator2:
    build:
      context: ./besu
      dockerfile: Dockerfile
    container_name: besu-validator2
    ports:
      - "8548:8545"
      - "30305:30303/tcp"
      - "30305:30303/udp"
    volumes:
      - ./node-configs/node2:/opt/besu/data
      - ./config:/opt/besu/config
    depends_on:
      - bootnode
    command: |
      --genesis-file=/opt/besu/config/genesis.json
      --data-path=/opt/besu/data
      --node-private-key-file=/opt/besu/data/key
      --bootnodes=enode://$(cat ./node-configs/bootnode/enode)@bootnode:30303
      --rpc-http-enabled=true
      --rpc-http-host=0.0.0.0
      --rpc-http-port=8545
      --rpc-http-cors-origins="*"
      --host-allowlist="*"
      --p2p-enabled=true
      --p2p-host=0.0.0.0
      --p2p-port=30303
      --network-id=1337
      --logging=INFO
      --permissions-accounts-config-enabled=true
      --permissions-accounts-config-file=/opt/besu/config/permissions.json
    networks:
      - besu-network

  api-server:
    build:
      context: ../api
      dockerfile: Dockerfile
    container_name: expense-api
    ports:
      - "3000:3000"
    environment:
      - BLOCKCHAIN_RPC_URL=http://bootnode:8545
      - NODE_ENV=development
    depends_on:
      - bootnode
      - validator1
      - validator2
    networks:
      - besu-network

networks:
  besu-network:
    driver: bridge